### ISSUE TITLE
PicoBoy Communication Software does not start

### ISSUE THREAD

**Issue by Hamuza11** [HalloSpaceBoy5/PicoBoy#1]
Hi,
i'm running a Ubuntu 20.04 image on my computer. When I try to start the PicoBoy Communication Software, it does not load.
If I run it in a terminal it says:

`[122670] Error loading Python lib '/tmp/_MEITdSVBS/libpython3.10.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.35' not found (required by /tmp/_MEITdSVBS/libpython3.10.so.1.0)`.

I would really appreciate some help!

**Comment by HalloSpaceBoy5** [comment]
Hi! Your Ubuntu installation may be out of date, as it is missing the library GLIB_C (GNU C Library) v2.35. This is a core C library required by the Python-based backend of PicoBoy Communication Software. Please try updating your library, as Ubuntu 20.04 comes with GLIB_C v2.31. I highly recommend using either the Windows or Mac versions of the software, as they are much more compatible with different OS versions. (If you try to run PicoBoy Communication Software on MacOS Sequoia, make sure to use the prerelease version. The update broke one of its main drivers.) If you have any other questions, feel free to ask!
