### ISSUE TITLE
Picoboy communication software for Debian 11

### ISSUE THREAD

**Issue by Hamuza11** [HalloSpaceBoy5/PicoBoy#2]
Hi, it's me again.
I find it restricting that I need Debian 11 to run the Picoboy communication software. Could you please publish the source?

**Comment by HalloSpaceBoy5** [comment]
Thank you for your feedback! I have been contemplating putting PicoBoy Communication Software up on GitHub for a while now, and I think now is a good time. I'll need a little time to clean up the code and get everything organized, but you can expect to see it up sometime within the month.

**Comment by Hamuza11** [comment]
BTW: I have a very old and altered version of the Picoboy OS. Cause I'm using a different setup. Could you please try to update it for me? It would mean a lot to me. Link: https://github.com/Hamuza11/Gamer2040

**Comment by HalloSpaceBoy5** [comment]
I’m sorry, but unofficial PBOS setups for non-PicoBoy devices are not officially supported by me or the PicoBoy project. Once the source code for PicoBoy Communication Software is up, feel free to mod it to support your custom flavor of PBOS and take a look at the newer releases of the source code to add the features you want from them. If you have any features you have modded in that you would like to see, feel free to tell me where you put them and I will take a look, I may include them in the official PBOS if that would be ok with you.

**Comment by Hamuza11** [comment]
No worries! I just needed an update.😁
